<script setup lang="ts">
import {
  Aim,
  ArrowRight,
  Avatar,
  Bell,
  ChatDotRound,
  Check,
  CircleCheck,
  CircleClose,
  Clock,
  Close,
  Coin,
  Collection,
  Connection,
  CopyDocument,
  Cpu,
  DataAnalysis,
  DataBoard,
  Delete,
  Document,
  Download,
  Edit,
  EditPen,
  Failed,
  Files,
  Finished,
  Grid,
  Help,
  Hide,
  InfoFilled,
  Key,
  Link,
  Loading,
  Lock,
  MagicStick,
  Management,
  Menu,
  MoreFilled,
  Operation,
  Plus,
  Promotion,
  Refresh,
  Search,
  Setting,
  Share,
  SwitchButton,
  Tools,
  Upload,
  User,
  UserFilled,
  VideoPause,
  VideoPlay,
  View,
  Warning,
  WarningFilled,
} from '@element-plus/icons-vue'
import { computed, type Component } from 'vue'

const props = withDefaults(
  defineProps<{ name: string; size?: number | string; color?: string }>(),
  { size: 18, color: '' },
)

const iconMap: Record<string, Component> = {
  account_circle: UserFilled,
  activity: DataAnalysis,
  add: Plus,
  admin_panel_settings: Management,
  article: Files,
  arrow_forward: ArrowRight,
  auto_awesome: MagicStick,
  block: CircleClose,
  bug_report: Failed,
  check: Check,
  check_circle: CircleCheck,
  chevron_right: ArrowRight,
  close: Close,
  content_copy: CopyDocument,
  corporate_fare: Management,
  data_object: DataAnalysis,
  delete: Delete,
  devices: DataBoard,
  download: Download,
  drafts: Document,
  drag_indicator: Operation,
  edit: Edit,
  edit_note: EditPen,
  error: CircleClose,
  fact_check: Finished,
  filter_alt_off: Search,
  forum: ChatDotRound,
  gpp_bad: WarningFilled,
  gpp_maybe: Warning,
  help: Help,
  history: Clock,
  home: Grid,
  hub: Share,
  info: InfoFilled,
  key: Key,
  link: Link,
  link_off: CircleClose,
  lock: Lock,
  logout: SwitchButton,
  mark_email_read: Bell,
  campaign: Promotion,
  memory: Cpu,
  menu: Menu,
  more_vert: MoreFilled,
  pause: VideoPause,
  pause_circle: VideoPause,
  person: User,
  person_add: Avatar,
  phonelink_erase: CircleClose,
  play_arrow: VideoPlay,
  play_circle: VideoPlay,
  publish: Upload,
  refresh: Refresh,
  replay: Refresh,
  restore: Refresh,
  save: Collection,
  schedule: Clock,
  science: Aim,
  search: Search,
  search_off: Search,
  security: Lock,
  settings_input_antenna: Connection,
  settings_suggest: Tools,
  shield: Lock,
  smart_toy: Cpu,
  stop: CircleClose,
  sync: Loading,
  sync_problem: Warning,
  toll: Coin,
  tune: Setting,
  upload_file: Upload,
  verified: CircleCheck,
  verified_user: CircleCheck,
  visibility: View,
  visibility_off: Hide,
  vpn_key: Key,
  warning: WarningFilled,
}

const icon = computed(() => iconMap[props.name] ?? InfoFilled)
const iconColor = computed(() => {
  const colors: Record<string, string> = {
    primary: 'var(--app-action-primary)',
    positive: 'var(--app-action-success)',
    negative: 'var(--app-action-danger)',
    warning: 'var(--app-action-warning)',
    info: 'var(--app-text-secondary)',
  }
  return colors[props.color] || props.color || undefined
})
</script>

<template>
  <el-icon :size="size" :color="iconColor" aria-hidden="true"><component :is="icon" /></el-icon>
</template>
