"""add article revision proposals

Revision ID: 0540e296bea2
Revises: 2c9c44380b1e
Create Date: 2026-08-31 15:56:43.252875
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0540e296bea2"
down_revision: str | None = "2c9c44380b1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article_revisions",
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("article_id", sa.String(length=36), nullable=False),
        sa.Column("base_version_id", sa.String(length=36), nullable=False),
        sa.Column("base_version_no", sa.Integer(), nullable=False),
        sa.Column("base_content_hash", sa.String(length=64), nullable=False),
        sa.Column("selection_from", sa.Integer(), nullable=True),
        sa.Column("selection_to", sa.Integer(), nullable=True),
        sa.Column("selected_text", sa.Text(), nullable=False),
        sa.Column("instruction", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("model_route_snapshot", sa.JSON(), nullable=False),
        sa.Column("prompt_version_id", sa.String(length=36), nullable=True),
        sa.Column("replacement_text", sa.Text(), nullable=True),
        sa.Column("provider_request_id", sa.String(length=120), nullable=True),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.Column("quota_reserved", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["base_version_id"],
            ["article_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_id",
            "article_id",
            "idempotency_key",
            name="uq_article_revision_owner_article_idem",
        ),
    )
    op.create_index(
        "ix_article_revisions_owner_status_created",
        "article_revisions",
        ["owner_id", "status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_article_revisions_owner_status_created", table_name="article_revisions")
    op.drop_table("article_revisions")
    # ### end Alembic commands ###
